#!/usr/bin/env python3
"""
diff_context.py — Show what changed between old and new context files before installing.

Usage:
    python scripts/diff_context.py --old .ai-context/ --new /tmp/vca/output/
"""
import argparse, sys, difflib
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from utils import now_date

FILES_TO_DIFF = [
    "CONTEXT.md", "DECISIONS.md", "PATTERNS.md",
    "STYLE.md", "ANTI-PATTERNS.md", "SESSION-STARTER.md"
]

GREEN = "\033[92m"
RED = "\033[91m"
CYAN = "\033[96m"
BOLD = "\033[1m"
RESET = "\033[0m"


def diff_files(old_dir, new_dir):
    old_path = Path(old_dir)
    new_path = Path(new_dir)
    results = []

    for fname in FILES_TO_DIFF:
        old_file = old_path / fname
        new_file = new_path / fname

        if not new_file.exists():
            results.append((fname, "MISSING_NEW", [], []))
            continue
        if not old_file.exists():
            results.append((fname, "NEW_FILE", [], new_file.read_text().splitlines()))
            continue

        old_lines = old_file.read_text(encoding="utf-8").splitlines()
        new_lines = new_file.read_text(encoding="utf-8").splitlines()

        diff = list(difflib.unified_diff(
            old_lines, new_lines,
            fromfile=f"old/{fname}", tofile=f"new/{fname}",
            lineterm=""
        ))
        results.append((fname, "DIFF", old_lines, diff))

    return results


def print_diff_summary(results):
    print(f"\n{BOLD}Context Diff Summary — {now_date()}{RESET}\n")
    changed = 0
    for fname, status, old_lines, diff in results:
        if status == "MISSING_NEW":
            print(f"  {RED}✗ MISSING{RESET}  {fname}")
        elif status == "NEW_FILE":
            print(f"  {GREEN}+ NEW{RESET}     {fname} ({len(diff)} lines)")
            changed += 1
        elif diff:
            adds = sum(1 for l in diff if l.startswith("+") and not l.startswith("+++"))
            dels = sum(1 for l in diff if l.startswith("-") and not l.startswith("---"))
            print(f"  {CYAN}~ CHANGED{RESET}  {fname}  ({GREEN}+{adds}{RESET} / {RED}-{dels}{RESET})")
            changed += 1
        else:
            print(f"  ✓ unchanged  {fname}")

    print(f"\n  {changed} file(s) would change.\n")
    return changed


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--old", required=True, help="Existing .ai-context/ directory")
    parser.add_argument("--new", required=True, help="New generated output directory")
    parser.add_argument("--verbose", action="store_true", help="Show full diff")
    args = parser.parse_args()

    results = diff_files(args.old, args.new)
    changed = print_diff_summary(results)

    if args.verbose and changed:
        for fname, status, old_lines, diff in results:
            if diff and status == "DIFF":
                print(f"\n{'─'*60}")
                print(f"  {fname}")
                print(f"{'─'*60}")
                for line in diff[:50]:
                    if line.startswith("+"):
                        print(f"{GREEN}{line}{RESET}")
                    elif line.startswith("-"):
                        print(f"{RED}{line}{RESET}")
                    elif line.startswith("@@"):
                        print(f"{CYAN}{line}{RESET}")
                    else:
                        print(line)
                if len(diff) > 50:
                    print(f"  ... ({len(diff) - 50} more lines)")

    sys.exit(0 if changed == 0 else 1)


if __name__ == "__main__":
    main()


# ─────────────────────────────────────────────────────────────────────────────
# export_context.py — Export all context files as a single portable markdown
# ─────────────────────────────────────────────────────────────────────────────

def export_context(input_dir, output_path):
    """Bundle all .ai-context/ files into one portable document."""
    src = Path(input_dir)
    sections = []

    order = [
        "SESSION-STARTER.md",
        "CONTEXT.md",
        "DECISIONS.md",
        "PATTERNS.md",
        "STYLE.md",
        "ANTI-PATTERNS.md",
    ]

    for fname in order:
        fpath = src / fname
        if fpath.exists():
            content = fpath.read_text(encoding="utf-8")
            sections.append(f"---\n# 📄 {fname}\n\n{content}")

    # Any extra files not in order
    for fpath in sorted(src.glob("*.md")):
        if fpath.name not in order and fpath.name != "UPDATE-LOG.md":
            content = fpath.read_text(encoding="utf-8")
            sections.append(f"---\n# 📄 {fpath.name}\n\n{content}")

    header = f"""# AI Context Export
*Exported: {now_date()}*
*Generated by Vibe Context Architect*

This file contains the complete AI context for this project.
Paste it at the start of an AI chat session or upload as a document.

"""
    combined = header + "\n\n".join(sections)

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text(combined, encoding="utf-8")
    print(f"  → Exported to: {output_path}", file=sys.stderr)
    print(f"  → Size: {len(combined)} chars (~{len(combined)//4} tokens)", file=sys.stderr)
    return output_path


if __name__ == "__main__":
    # When run as export_context.py
    import sys
    if len(sys.argv) > 1 and sys.argv[1] == "--export":
        parser = argparse.ArgumentParser()
        parser.add_argument("--input", required=True)
        parser.add_argument("--output", required=True)
        args = parser.parse_args(sys.argv[2:])
        export_context(args.input, args.output)
