#!/usr/bin/env python3
"""
generate_context.py — Generate all .ai-context/ files from synthesized data.

Usage:
    python scripts/generate_context.py \
        --scan scan_result.json \
        --configs config_facts.json \
        --annotations annotations.json \
        --conventions conventions.json \
        --output /tmp/vca/output/
"""
import argparse, sys, json
from pathlib import Path
from datetime import date

sys.path.insert(0, str(Path(__file__).parent))
from utils import load_json, save_text, now_date, VCA_VERSION, count_tokens_approx


def generate_context_md(scan, configs, conventions):
    project = scan.get("project_name", "My Project")
    stack = scan.get("stack", {})
    scripts = scan.get("scripts", {})
    structure = scan.get("directory_map", {})

    # Format stack table
    stack_rows = []
    for layer, val in stack.items():
        if isinstance(val, list):
            val = ", ".join(val)
        stack_rows.append(f"| {layer.replace('_', ' ').title()} | {val} | — |")

    # Directory purposes (top-level dirs only)
    dir_purposes = []
    dir_purpose_map = {
        "src": "Main source code",
        "app": "Next.js App Router pages and layouts",
        "pages": "Next.js Pages Router",
        "components": "Shared React components",
        "lib": "Utility functions, configs, and shared logic",
        "hooks": "Custom React hooks",
        "utils": "Helper functions",
        "services": "Business logic and data access layer",
        "store": "Global state stores",
        "stores": "Global state stores",
        "types": "TypeScript type definitions",
        "api": "API routes",
        "server": "Server-side code",
        "prisma": "Database schema and migrations",
        "public": "Static assets served directly",
        "styles": "Global stylesheets",
        "contexts": "React context providers",
        "middleware": "Request middleware",
        "config": "App configuration",
        "features": "Feature-based modules",
        "modules": "Feature-based modules",
        "layouts": "Page layout components",
    }
    for dirname in structure.keys():
        clean = dirname.rstrip("/")
        if clean in dir_purpose_map:
            dir_purposes.append(f"- `{dirname}` — {dir_purpose_map[clean]}")
        elif not dirname.startswith(".") and dirname not in ("node_modules/", "dist/", "build/"):
            dir_purposes.append(f"- `{dirname}` — [Purpose unknown — update this]")

    # Extract commands
    pkg = configs.get("package", {})
    dev_cmd = pkg.get("dev_command", "npm run dev")
    build_cmd = pkg.get("build_command", "npm run build")
    pkg_manager = stack.get("package_manager", "npm")
    install_cmd = f"{pkg_manager} install"

    # Prisma info
    prisma = configs.get("prisma", {})
    models_section = ""
    if prisma.get("models"):
        model_rows = "\n".join(f"- **{m}**" for m in prisma["models"][:10])
        models_section = f"""
## 📊 Data Models

Core entities in the database:

{model_rows}
{"*(and more — see `prisma/schema.prisma`)*" if len(prisma["models"]) > 10 else ""}

**Database conventions:**
- ID strategy: {prisma.get("id_strategy", "unknown")}
- Soft delete: {"Yes (`deletedAt` field)" if prisma.get("soft_delete") else "No (hard delete)"}
- Audit fields: {"Yes (`createdAt`, `updatedAt` on all models)" if prisma.get("audit_fields") else "Not detected"}
"""

    # Env vars
    env_info = configs.get("env", {})
    env_section = ""
    if env_info.get("env_vars"):
        env_rows = "\n".join(f"{v}=" for v in env_info["env_vars"][:15])
        env_section = f"""
## 🔑 Environment Variables

Copy from `{env_info.get("source_file", ".env.example")}`:

```bash
{env_rows}
```
"""

    # Conventions summary
    conv = conventions.get("conventions", {}) if conventions else {}
    naming = conv.get("naming", {})
    key_conventions = []
    for k, v in naming.items():
        if v:
            key_conventions.append(f"- **{k.replace('_', ' ').title()}:** `{v}`")

    conventions_section = ""
    if key_conventions:
        conventions_section = f"""
## 📐 Key Conventions

{chr(10).join(key_conventions[:8])}

*See `.ai-context/STYLE.md` for complete style guide.*
"""

    return f"""# {project} — AI Context

> **Generated by Vibe Context Architect** on {now_date()}
> *Update: Re-run `vibe-context-architect` when the project changes significantly*

---

## 🏗️ Tech Stack

| Layer | Technology | Version |
|---|---|---|
{chr(10).join(stack_rows)}

---

## 📁 Project Structure

```
{project}/
{chr(10).join(list(structure.keys())[:15])}
```

### Directory Purposes

{chr(10).join(dir_purposes[:15]) or "*(Run scan to detect directory purposes)*"}

---

## 🚀 Running the Project

```bash
{install_cmd}       # Install dependencies
{dev_cmd}           # Start dev server
{build_cmd}         # Build for production
```

{f"Additional scripts: {json.dumps(scripts, indent=2)}" if scripts else ""}
{models_section}
{env_section}
{conventions_section}
---

## ⚡ Project State

- **Files:** {scan.get("counts", {}).get("source_files", "?")} source files, {scan.get("counts", {}).get("test_files", "?")} test files
- **Size:** {scan.get("classification", "unknown")}
- **Entry points:** {", ".join(f"`{e}`" for e in scan.get("entry_points", ["unknown"]))}

---

*Full patterns: `.ai-context/PATTERNS.md` | Decisions: `.ai-context/DECISIONS.md`*
"""


def generate_patterns_md(scan, configs, conventions):
    project = scan.get("project_name", "My Project")
    conv = conventions.get("conventions", {}) if conventions else {}
    stack = scan.get("stack", {})

    # Determine language for code blocks
    lang = "typescript" if "TypeScript" in str(stack.get("language", "")) else "javascript"

    # Build pattern sections from conventions
    patterns_sections = []

    api_pattern = conv.get("api_patterns", {})
    response_shape = api_pattern.get("response_shape", "{ data: T | null, error: string | null }")

    # Determine framework-specific patterns
    framework = str(stack.get("frontend", ""))

    if "Next.js" in framework and "App Router" in framework:
        patterns_sections.append(f"""## Pattern: API Route Handler (Next.js App Router)

**When to use:** Every new API endpoint in `src/app/api/`

```{lang}
// src/app/api/example/route.ts
import {{ NextRequest, NextResponse }} from "next/server"

export async function GET(req: NextRequest) {{
  try {{
    const data = await exampleService.getAll()
    return NextResponse.json({{ data, error: null }})
  }} catch (error) {{
    return NextResponse.json(
      {{ data: null, error: (error as Error).message }},
      {{ status: 500 }}
    )
  }}
}}
```

**Response shape:** `{response_shape}`
""")

    # State pattern
    state_tool = str(stack.get("state", ""))
    if "Zustand" in state_tool:
        patterns_sections.append(f"""## Pattern: Zustand Store

**When to use:** Global state shared across multiple components

```{lang}
// src/store/example.store.ts
import {{ create }} from "zustand"

interface ExampleState {{
  items: Item[]
  isLoading: boolean
  setItems: (items: Item[]) => void
  addItem: (item: Item) => void
}}

export const useExampleStore = create<ExampleState>()((set) => ({{
  items: [],
  isLoading: false,
  setItems: (items) => set({{ items }}),
  addItem: (item) => set((state) => ({{ items: [...state.items, item] }})),
}}))
```
""")

    # Data fetching pattern
    fetching = str(stack.get("data_fetching", ""))
    if "TanStack" in fetching:
        patterns_sections.append(f"""## Pattern: Data Fetching with TanStack Query

**When to use:** All server data fetching in client components

```{lang}
// Hook pattern
export function useUsers() {{
  return useQuery({{
    queryKey: ["users"],
    queryFn: () => fetch("/api/users").then(r => r.json()),
  }})
}}

// In component
const {{ data, isLoading, error }} = useUsers()
```
""")

    # Component pattern
    component_export = conv.get("structure", {}).get("component_exports", "named export")
    props_pattern = conv.get("structure", {}).get("props_interface", "ComponentNameProps interface above component")

    patterns_sections.append(f"""## Pattern: React Component Anatomy

**When to use:** Every new React component

```{lang}
// Named export, props interface above component
interface ExampleComponentProps {{
  title: string
  onAction?: () => void
}}

export function ExampleComponent({{ title, onAction }}: ExampleComponentProps) {{
  return (
    <div>
      <h2>{{title}}</h2>
      {{onAction && <button onClick={{onAction}}>Action</button>}}
    </div>
  )
}}
```

**Convention:** {component_export} | {props_pattern}
""")

    # Error handling
    error_style = conv.get("code_style", {}).get("error_handling", "try-catch with toast")
    patterns_sections.append(f"""## Pattern: Error Handling

**Convention:** {error_style}

```{lang}
async function handleAction() {{
  try {{
    const result = await someAsyncOperation()
    // handle success
  }} catch (error) {{
    // Always handle errors — never silent catch
    console.error("Operation failed:", error)
    toast.error((error as Error).message || "Something went wrong")
  }}
}}
```
""")

    return f"""# Code Patterns — {project}

Real patterns from this codebase. Use these as templates for new code.
*Updated: {now_date()}*

---

{chr(10).join(patterns_sections)}

---

## Import Convention

```{lang}
// 1. External packages
import {{ useState }} from "react"
import {{ useQuery }} from "@tanstack/react-query"

// 2. Internal aliases (@/ = src/)
import {{ Button }} from "@/components/ui/button"
import {{ userService }} from "@/services/user.service"

// 3. Relative imports (same directory only)
import {{ formatDate }} from "./utils"
```

---

*More patterns extracted from your codebase — add domain-specific patterns here as you build.*
"""


def generate_style_md(scan, configs, conventions):
    project = scan.get("project_name", "My Project")
    conv = conventions.get("conventions", {}) if conventions else {}
    naming = conv.get("naming", {})
    ts_config = configs.get("typescript", {})
    linting = configs.get("linting", {})

    # Build naming table
    naming_rows = []
    naming_display = {
        "component_files": "Component files",
        "non_component_files": "Utility/hook files",
        "component_functions": "Component names",
        "utility_functions": "Function names",
        "react_hooks": "Hook names",
        "constants": "Constants",
        "types": "Types / Interfaces",
        "api_routes": "API routes",
        "env_variables": "Environment vars",
    }
    for key, label in naming_display.items():
        val = naming.get(key) or conv.get("naming", {}).get(key)
        if val:
            naming_rows.append(f"| {label} | `{val}` |")

    # TypeScript rules
    ts_rules = []
    if ts_config.get("strict"):
        ts_rules.append("- **Strict mode ON** — no implicit any, strict null checks, etc.")
    if ts_config.get("no_any") or linting.get("no_any"):
        ts_rules.append("- **No `any` type** — use `unknown` with type guards, or proper typing")
    if ts_config.get("exact_optional"):
        ts_rules.append("- **Exact optional properties** — `{ a?: string }` means `string | undefined`, not `string | undefined | null`")

    aliases = ts_config.get("import_aliases", {})
    alias_examples = "\n".join(f"// {k} → {v}" for k, v in list(aliases.items())[:5])

    hard_rules = linting.get("hard_error_rules", [])[:8]
    linting_section = ""
    if hard_rules:
        linting_section = f"""
## Linting Rules (Enforced as Errors)

These will fail your build if violated:

```
{chr(10).join(f"- {r}" for r in hard_rules)}
```
"""

    return f"""# Code Style Guide — {project}

*These conventions are enforced in this project. Updated: {now_date()}*

---

## Naming Conventions

| Element | Convention |
|---|---|
{chr(10).join(naming_rows) or "| *(Run full analysis to extract naming conventions)* | — |"}

---

## TypeScript Rules

{chr(10).join(ts_rules) or "*(Run TypeScript config extraction for detailed rules)*"}

### Import Aliases

```typescript
{alias_examples or "// @/ → src/ (common alias)"}
```
{linting_section}

---

## Code Style Principles

{chr(10).join(f"- {r}" for r in (conventions.get("constraints_hard", []) if conventions else [])[:6]) or "*(Extracted from your codebase conventions)*"}

---

## File Organization

```
Component folder example:
components/
  UserCard/
    UserCard.tsx       ← Component
    UserCard.test.tsx  ← Co-located test
    index.ts           ← Barrel export
```

---

*See `.ai-context/PATTERNS.md` for code examples of each pattern.*
"""


def generate_antipatterns_md(scan, configs, annotations, conventions):
    project = scan.get("project_name", "My Project")
    stack = scan.get("stack", {})
    linting = configs.get("linting", {})
    conv = conventions.get("conventions", {}) if conventions else {}

    items = []

    # From hard linting rules
    hard_rules = linting.get("hard_error_rules", [])
    if "no-console" in hard_rules or linting.get("no_console"):
        items.append({
            "title": "Using `console.log()` in production code",
            "reason": "ESLint `no-console` is set to error in this project.",
            "instead": "Use the project's logger utility, or remove debug logs before committing.",
            "trigger": "debugging issues",
            "bad": "console.log('user:', user)",
            "good": "logger.debug('user loaded', { userId: user.id })",
        })
    if linting.get("no_any"):
        items.append({
            "title": "TypeScript `any` type",
            "reason": "This project enforces `@typescript-eslint/no-explicit-any: error`.",
            "instead": "Use `unknown` with type guards, or define a proper type.",
            "trigger": "complex generic type problems",
            "bad": "function parse(data: any) { ... }",
            "good": "function parse(data: unknown) { if (typeof data === 'object') { ... } }",
        })

    # From architecture conventions
    code_style = conv.get("code_style", {})
    if "async/await" in str(code_style.get("async_pattern", "")):
        items.append({
            "title": "Promise `.then()` chains",
            "reason": "This codebase uses async/await exclusively — .then() chains are inconsistent.",
            "instead": "Use async/await for all asynchronous code.",
            "trigger": "API calls, file operations",
            "bad": "fetchUser(id).then(user => setUser(user)).catch(handleError)",
            "good": "const user = await fetchUser(id) // in async function with try/catch",
        })

    # Framework-specific anti-patterns
    framework = str(stack.get("frontend", ""))
    if "Next.js" in framework:
        items.append({
            "title": "Adding `'use client'` to every component",
            "reason": "Next.js App Router defaults to Server Components — adding 'use client' unnecessarily disables server-rendering benefits.",
            "instead": "Only add 'use client' when the component uses browser APIs, event handlers, or React state/effects.",
            "trigger": "creating new components",
            "bad": "'use client'\nexport function StaticCard({ title }) { return <div>{title}</div> }",
            "good": "// No 'use client' needed for pure rendering\nexport function StaticCard({ title }) { return <div>{title}</div> }",
        })

    # From annotation mining
    anti_candidates = annotations.get("anti_pattern_candidates", [])[:5]
    for cand in anti_candidates:
        items.append({
            "title": f"Known issue: {cand['description'][:60]}",
            "reason": f"Marked as `{cand['source']}` in `{cand['file']}` line {cand['line']}.",
            "instead": "Fix the underlying issue before replicating this pattern.",
            "trigger": "similar features",
            "bad": None,
            "good": None,
        })

    # From explicit prohibitions in code
    prohibitions = annotations.get("prohibitions", [])[:3]
    for p in prohibitions:
        items.append({
            "title": f"Explicit prohibition: {p['text'][:60]}",
            "reason": f"Explicitly marked in code at `{p['file']}` line {p['line']}.",
            "instead": "Follow the note in the source file.",
            "trigger": "related code area",
            "bad": None,
            "good": None,
        })

    # Generic always-include items
    items.append({
        "title": "Hardcoded secrets, API keys, or credentials",
        "reason": "Security risk — these get committed to git.",
        "instead": "Use environment variables from `.env.local` (never commit this file).",
        "trigger": "integrating external services",
        "bad": "const apiKey = 'sk_live_abc123...'",
        "good": "const apiKey = process.env.STRIPE_SECRET_KEY",
    })

    # Render sections
    sections = []
    for i, item in enumerate(items[:10], 1):
        code_block = ""
        if item.get("bad") and item.get("good"):
            lang = "typescript"
            code_block = f"""
```{lang}
// ❌ Wrong
{item["bad"]}

// ✅ Right
{item["good"]}
```"""

        sections.append(f"""## ❌ {i}. {item["title"]}

**Why it's wrong here:** {item["reason"]}
**Instead:** {item["instead"]}
**AI often does this when:** {item.get("trigger", "making suggestions")}{code_block}

---""")

    return f"""# AI Guardrails — {project}

Read before making any code suggestions. These are the things AI assistants commonly
get wrong in THIS project specifically.

*Updated: {now_date()}*

---

{chr(10).join(sections)}

## Legacy Code Warning

Some older files may violate current conventions. If you see a pattern that conflicts
with this document, follow this document — not the legacy code.

---

*More guardrails added as the project evolves. Update `.ai-context/ANTI-PATTERNS.md` when you find AI making repeated mistakes.*
"""


def generate_decisions_md(scan, configs, conventions):
    project = scan.get("project_name", "My Project")
    stack = scan.get("stack", {})

    decisions = []
    i = 1

    # Framework decision
    frontend = str(stack.get("frontend", ""))
    if frontend:
        decisions.append(f"""## ADR-{i:03d}: {frontend} as Frontend Framework

**Status:** Active
**Date:** {now_date()} (inferred)

### Decision
Use {frontend} as the primary frontend framework.

### Context & Why
*(Update this with your actual reasoning — inferred from codebase)*

### Consequences
- File structure follows {frontend} conventions
- Deployment optimized for {frontend}'s requirements
- See `PATTERNS.md` for framework-specific patterns

---""")
        i += 1

    # TypeScript decision
    ts_config = configs.get("typescript", {})
    if ts_config.get("strict"):
        decisions.append(f"""## ADR-{i:03d}: TypeScript Strict Mode

**Status:** Active

### Decision
TypeScript strict mode is enabled (`"strict": true` in tsconfig.json).

### Context & Why
Strict mode catches more bugs at compile time. The tradeoff (more verbose code) is
worth the reliability gains, especially as the project grows.

### Consequences
- No implicit `any` types
- Null/undefined must be handled explicitly
- All function parameters must be typed

---""")
        i += 1

    # Database decision
    db = str(stack.get("database", ""))
    if db:
        decisions.append(f"""## ADR-{i:03d}: {db} for Database Access

**Status:** Active

### Decision
Use {db} for all database operations.

### Context & Why
*(Update with your actual reasoning)*

### Consequences
- All DB queries go through {db} — no raw SQL in application code
- Schema changes managed through migrations
- See service layer pattern in `PATTERNS.md`

---""")
        i += 1

    # Auth decision
    auth = str(stack.get("auth", ""))
    if auth:
        decisions.append(f"""## ADR-{i:03d}: {auth} for Authentication

**Status:** Active

### Decision
Use {auth} for authentication and session management.

### Context & Why
*(Update with your actual reasoning)*

### Consequences
- Never implement custom auth logic — use {auth} abstractions
- See `ANTI-PATTERNS.md` for auth-related guardrails

---""")
        i += 1

    # From annotations - HACKs become known technical decisions
    annotations_path_note = ""
    if conventions:
        for item in conventions.get("anti_patterns", [])[:3]:
            if "HACK" in str(item):
                decisions.append(f"""## ADR-{i:03d}: Workaround — {item.get("pattern", "Known workaround")[:50]}

**Status:** Temporary

### Decision
{item.get("pattern", "")}

### Context & Why
{item.get("why", "Temporary workaround — see source file for context.")}

### Consequences
- {item.get("instead", "Replace with proper implementation when time permits.")}

---""")
                i += 1

    return f"""# Architecture Decision Log — {project}

These decisions define WHY things are built the way they are.
When in doubt, follow these. When a decision changes, update this log.

*Updated: {now_date()}*

---

{chr(10).join(decisions)}

## Pending Decisions

- [ ] *(Add decisions here as you make them)*

---

*Document decisions here as you make them — helps AI understand your WHY, not just your WHAT.*
"""


def generate_session_starter_md(scan, configs, conventions, antipatterns_md):
    project = scan.get("project_name", "My Project")
    stack = scan.get("stack", {})
    conv = conventions.get("conventions", {}) if conventions else {}

    # Format stack one-liner
    parts = []
    for k in ["frontend", "language", "database", "auth", "styling", "state"]:
        v = stack.get(k)
        if v:
            if isinstance(v, list): v = " + ".join(v)
            parts.append(str(v))
    stack_line = " · ".join(parts[:6])

    # Compact directory map (top 8 dirs)
    dir_map = scan.get("directory_map", {})
    dir_lines = [f"  {d}" for d in list(dir_map.keys())[:8] if not d.startswith(".")]

    # Top conventions
    naming = conv.get("naming", {})
    code_style = conv.get("code_style", {})
    structure = conv.get("structure", {})

    top_conventions = []
    for k, v in list(naming.items())[:4]:
        if v: top_conventions.append(f"- {k.replace('_', ' ').title()}: `{v}`")
    for k, v in list(code_style.items())[:3]:
        if v: top_conventions.append(f"- {k.replace('_', ' ').title()}: {v}")
    for k, v in list(structure.items())[:2]:
        if v: top_conventions.append(f"- {k.replace('_', ' ').title()}: {v}")

    # Top 5 anti-patterns (extract from ANTI-PATTERNS.md)
    anti_lines = []
    for line in antipatterns_md.splitlines():
        if line.startswith("## ❌"):
            title = line.replace("## ❌ ", "").strip()
            # Remove leading number
            import re
            title = re.sub(r"^\d+\. ", "", title)
            anti_lines.append(f"- ❌ {title}")
        if len(anti_lines) >= 5:
            break

    # Prisma models
    prisma = configs.get("prisma", {})
    models_line = ""
    if prisma.get("models"):
        models_line = f"\n## Data Models\nKey entities: {', '.join(f'`{m}`' for m in prisma['models'][:6])}"

    content = f"""# {project} — AI Context Starter

**Copy and paste this at the start of any new AI chat session.**

---

You are working on **{project}**.

## Stack
{stack_line}

## Project Structure
```
{chr(10).join(dir_lines)}
```
{models_line}

## Key Conventions (always follow)
{chr(10).join(top_conventions[:8]) or "- See `.ai-context/STYLE.md` for full conventions"}

## ❌ Never Do These
{chr(10).join(anti_lines[:5]) or "- See `.ai-context/ANTI-PATTERNS.md`"}

## Current Task
*[Describe what you're working on here]*

---
Full context: `.ai-context/CONTEXT.md`
Patterns: `.ai-context/PATTERNS.md`
Decisions: `.ai-context/DECISIONS.md`
"""

    # Trim to ~800 tokens if too long
    token_count = count_tokens_approx(content)
    if token_count > 900:
        # Trim conventions and anti-patterns
        content = content.replace(
            chr(10).join(top_conventions[:8]),
            chr(10).join(top_conventions[:5])
        )

    return content


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--scan", required=True)
    parser.add_argument("--configs", required=True)
    parser.add_argument("--annotations", required=True)
    parser.add_argument("--conventions", default=None)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    scan = load_json(args.scan)
    configs = load_json(args.configs)
    annotations = load_json(args.annotations)
    conventions = load_json(args.conventions) if args.conventions and Path(args.conventions).exists() else None

    out = args.output.rstrip("/")

    print(f"Generating context files for: {scan.get('project_name', '?')}", file=sys.stderr)

    # Generate all 6 files
    context_md = generate_context_md(scan, configs, conventions)
    save_text(context_md, f"{out}/CONTEXT.md")

    patterns_md = generate_patterns_md(scan, configs, conventions)
    save_text(patterns_md, f"{out}/PATTERNS.md")

    style_md = generate_style_md(scan, configs, conventions)
    save_text(style_md, f"{out}/STYLE.md")

    antipatterns_md = generate_antipatterns_md(scan, configs, annotations, conventions)
    save_text(antipatterns_md, f"{out}/ANTI-PATTERNS.md")

    decisions_md = generate_decisions_md(scan, configs, conventions)
    save_text(decisions_md, f"{out}/DECISIONS.md")

    session_starter = generate_session_starter_md(scan, configs, conventions, antipatterns_md)
    save_text(session_starter, f"{out}/SESSION-STARTER.md")

    # Token count for SESSION-STARTER
    tokens = count_tokens_approx(session_starter)
    print(f"  SESSION-STARTER: ~{tokens} tokens {'✅' if tokens <= 900 else '⚠️ over limit'}", file=sys.stderr)
    print("  Context generation complete.", file=sys.stderr)


if __name__ == "__main__":
    main()
